<a href="https://colab.research.google.com/github/abdurahuman6669-ops/DSA/blob/main/abdu002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1

In [1]:
import numpy as np

arr = np.arange(10, 50)
reshaped = arr.reshape(4, 10)
last_column = reshaped[:, -1]

print("Reshaped array:\n", reshaped)
print("Last column:\n", last_column)


Reshaped array:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
Last column:
 [19 29 39 49]


2

In [ ]:
matrix1 = np.full((3, 3), 5)
matrix2 = np.arange(1, 10).reshape(3, 3)

added = matrix1 + matrix2
multiplied = matrix1 * matrix2
transposed = multiplied.T

print("Added:\n", added)
print("Element-wise multiplied:\n", multiplied)
print("Transpose:\n", transposed)


3


In [2]:
rand_arr = np.random.randint(10, 101, size=15)
modified = rand_arr.copy()
modified[modified > 50] = -1
replaced_count = np.sum(rand_arr > 50)

print("Original:\n", rand_arr)
print("Modified:\n", modified)
print("Count replaced:", replaced_count)


Original:
 [36 19 37 38 29 34 31 73 77 72 22 19 96 97 76]
Modified:
 [36 19 37 38 29 34 31 -1 -1 -1 22 19 -1 -1 -1]
Count replaced: 6


4

In [3]:
arr = np.random.rand(5, 4)
row_sums = arr.sum(axis=1)
max_row_index = np.argmax(row_sums)

# Normalize: (x - min) / (max - min) per row
row_min = arr.min(axis=1).reshape(-1, 1)
row_max = arr.max(axis=1).reshape(-1, 1)
normalized = (arr - row_min) / (row_max - row_min)

print("Array:\n", arr)
print("Row with max sum:", max_row_index)
print("Normalized:\n", normalized)


Array:
 [[0.66261429 0.01649012 0.71281395 0.94500258]
 [0.31682195 0.75436477 0.01017577 0.9967986 ]
 [0.10528124 0.83952737 0.48333169 0.04243807]
 [0.98428044 0.2606419  0.06566402 0.66539886]
 [0.87564032 0.88791883 0.43275889 0.17150496]]
Row with max sum: 4
Normalized:
 [[0.69587021 0.         0.74993483 1.        ]
 [0.31080385 0.75427912 0.         1.        ]
 [0.07884081 1.         0.55312951 0.        ]
 [1.         0.21225168 0.         0.65286754]
 [0.98286115 1.         0.364669   0.        ]]


5

In [6]:
arr = np.array([1, 3, 5, 3, 7, 1, 5, 5])
unique_elements = np.unique(arr)
duplicates = np.unique(arr[arr[np.isin(arr, arr[np.unique(np.where(np.bincount(arr) > 1)[0])])]])

from collections import Counter
duplicates = np.array([item for item, count in Counter(arr).items() if count > 1])

print("Unique elements:", unique_elements)
print("Duplicates:", duplicates)


Unique elements: [1 3 5 7]
Duplicates: [1 3 5]


6

In [7]:
arr = np.arange(1, 37).reshape(6, 6)
middle = arr[1:5, 1:5]
even_numbers = middle[middle % 2 == 0]

print("Middle 4x4:\n", middle)
print("Even numbers:\n", even_numbers)


Middle 4x4:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
Even numbers:
 [ 8 10 14 16 20 22 26 28]


7

In [8]:
arr = np.arange(12).reshape(3, 4)
reshaped = arr.reshape(2, 6)
flattened = reshaped.flatten()
reshaped_back = flattened.reshape(4, 3)

print("Original:\n", arr)
print("Reshaped (2x6):\n", reshaped)
print("Flattened:", flattened)
print("Reshaped to (4x3):\n", reshaped_back)


Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8

In [9]:
a = np.array([[1, 2], [3, 4]])
a = np.vstack([a, [5, 6]])
a = np.column_stack([a, [7, 8, 9]])

print("Final array:\n", a)


Final array:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


9

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

joined = np.concatenate([a, b, c])
reshaped = joined.reshape(3, 3)
diagonal = np.diag(reshaped)

print("Matrix:\n", reshaped)
print("Diagonal:", diagonal)


10

In [10]:
arr = np.arange(1, 21)
divisible = arr[(arr % 3 == 0) | (arr % 5 == 0)]

print("Values divisible by 3 or 5:", divisible)


Values divisible by 3 or 5: [ 3  5  6  9 10 12 15 18 20]
